[providers]
providers = ['php', 'node']

[phases.setup]
nixPkgs = [
  'php82',
  'php82Packages.composer',
  'nodejs_20',
  'git'
]

[phases.install]
cmds = [
  'composer install --ignore-platform-reqs --no-interaction --plugins-cli-args="--no-plugins" --prefer-dist --no-dev',
  'npm ci || npm install'
]

[phases.build]
cmds = [
  'npm run build'
]

[start]
cmd = 'php artisan serve --host=0.0.0.0 --port=8000'